import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Company",
  description: "Learn about Surface Crete, our material-led approach and our work across India.",
  alternates: { canonical: "/company" },
};

const principles = [
  ["01", "Material first", "We begin with the character of the material: its texture, depth, light response and the way it will age in a real space."],
  ["02", "Craft in every layer", "From substrate preparation to the final protective coat, careful application turns a specification into a surface that performs."],
  ["03", "Built around people", "A successful surface should support the people who inhabit it—at home, at work, in hospitality and in public life."],
];

export default function CompanyPage() {
  return (
    <main className="flex flex-1 flex-col gap-[5px] bg-[#171f25] text-[#f4f0e9] md:mx-[15px] md:w-[calc(100%-30px)]">
      <section className="relative min-h-[740px] overflow-hidden px-6 py-10 sm:px-10 lg:px-14 lg:py-14">
        <div className="absolute inset-0 opacity-45"><Image src="/images/projects/botique-hotel-mumbai-wall.png" alt="Textured Surface Crete wall finish" fill priority className="object-cover" sizes="100vw" /></div>
        <div className="absolute inset-0 bg-gradient-to-br from-[#171f25] via-[#171f25]/80 to-transparent" />
        <div className="relative mx-auto flex min-h-[650px] max-w-[1370px] flex-col justify-between">
          <p className="text-sm font-semibold uppercase tracking-[0.2em] text-white/60">Surface Crete — India</p>
          <div className="max-w-5xl"><p className="text-sm font-semibold uppercase tracking-[0.15em] text-[#d7bf90]">The studio behind the surface</p><h1 className="mt-6 text-[54px] font-light leading-[0.93] tracking-[-0.06em] sm:text-[84px] lg:text-[116px]">We make spaces feel <span className="italic">considered.</span></h1></div>
          <div className="grid gap-8 border-t border-white/30 pt-6 sm:grid-cols-[1fr_0.6fr]"><p className="max-w-xl text-[18px] leading-[1.6] text-white/80">Surface Crete brings together material knowledge, technical care and a belief that architecture should feel as good as it looks.</p><a href="#our-approach" className="self-end text-sm font-semibold uppercase tracking-[0.12em] text-[#d7bf90] sm:text-right">Our approach ↓</a></div>
        </div>
      </section>

      <section id="our-approach" className="bg-[#f3efe8] px-6 py-20 text-[#1d2830] sm:px-10 lg:px-14 lg:py-28"><div className="mx-auto grid max-w-[1370px] gap-12 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-sm font-semibold uppercase tracking-[0.15em] text-[#6a7375]">Who we are</p><h2 className="mt-5 text-[39px] font-light leading-[1.06] tracking-[-0.04em] sm:text-[55px]">A surface partner for ambitious spaces.</h2></div><div className="max-w-2xl space-y-6 text-[18px] leading-[1.75] text-[#4d575b]"><p>We work with architects, designers, contractors and homeowners to create mineral finishes that have a clear purpose. Every project starts with a conversation about the space, its use and the feeling it should create.</p><p>Our systems are selected and applied to bring continuity across floors, walls, wet areas, outdoor spaces and bespoke details—without losing the individuality of the material.</p></div></div></section>

      <section className="relative bg-[#c9b899] px-6 py-16 text-[#1d2830] sm:px-10 lg:px-14 lg:py-20"><div className="mx-auto max-w-[1370px]"><p className="text-sm font-semibold uppercase tracking-[0.15em] text-[#4d4840]">What guides our work</p><div className="mt-12 divide-y divide-[#1d2830]/30 border-y border-[#1d2830]/30">{principles.map(([number, title, copy]) => <article key={number} className="grid gap-5 py-8 sm:grid-cols-[90px_0.8fr_1.2fr] sm:items-start"><p className="text-sm font-semibold text-[#5e574c]">{number}</p><h3 className="text-[29px] font-light sm:text-[36px]">{title}</h3><p className="max-w-xl text-[16px] leading-[1.7] text-[#403d37]">{copy}</p></article>)}</div></div></section>

      <section className="bg-[#f3efe8] px-6 py-20 text-[#1d2830] sm:px-10 lg:px-14 lg:py-28"><div className="mx-auto grid max-w-[1370px] gap-12 lg:grid-cols-[0.75fr_1.25fr]"><div><p className="text-sm font-semibold uppercase tracking-[0.15em] text-[#6a7375]">What we bring</p><h2 className="mt-5 text-[39px] font-light leading-[1.06] tracking-[-0.04em] sm:text-[55px]">Technical depth without losing the human touch.</h2></div><div className="grid gap-4 sm:grid-cols-2"><div className="border-t border-[#1d2830]/30 pt-4"><p className="text-[22px] font-light">Specification support</p><p className="mt-3 text-[15px] leading-[1.7] text-[#566166]">We help turn an early material idea into a practical surface system with the right finish, substrate preparation and performance requirements.</p></div><div className="border-t border-[#1d2830]/30 pt-4"><p className="text-[22px] font-light">Sample-led decisions</p><p className="mt-3 text-[15px] leading-[1.7] text-[#566166]">Real samples make it easier to assess tone, texture and movement in the light and context of the project.</p></div><div className="border-t border-[#1d2830]/30 pt-4"><p className="text-[22px] font-light">Skilled application</p><p className="mt-3 text-[15px] leading-[1.7] text-[#566166]">Our process respects the craft behind hand-applied mineral finishes and the discipline needed for long-term performance.</p></div><div className="border-t border-[#1d2830]/30 pt-4"><p className="text-[22px] font-light">Aftercare guidance</p><p className="mt-3 text-[15px] leading-[1.7] text-[#566166]">We share straightforward advice on care, use and maintenance so each finish continues to look its best.</p></div></div></div></section>

      <section className="bg-[#171f25] px-6 py-20 sm:px-10 lg:px-14 lg:py-28"><div className="mx-auto grid max-w-[1370px] gap-5 lg:grid-cols-[1.2fr_0.8fr]"><div className="relative min-h-[520px] overflow-hidden"><Image src="/images/projects/hyderabad-villa-interior.png" alt="Surface Crete work in a Hyderabad villa" fill className="object-cover" sizes="(min-width: 1024px) 60vw, 100vw" /><div className="absolute bottom-0 left-0 p-7 text-sm font-semibold uppercase tracking-[0.13em] text-white/80">Material in context</div></div><div className="flex flex-col justify-between bg-[#27333b] p-7 sm:p-10"><div><p className="text-sm font-semibold uppercase tracking-[0.15em] text-[#d7bf90]">Our process</p><h2 className="mt-6 text-[39px] font-light leading-[1.08] tracking-[-0.04em] sm:text-[51px]">From first sample to final surface.</h2></div><ol className="mt-12 space-y-5 border-t border-white/30 pt-5 text-white/75">{['Understand the project', 'Recommend the right system', 'Create samples and mock-ups', 'Prepare and apply with care', 'Protect the finish and guide its care'].map((step, index) => <li key={step} className="flex gap-5"><span className="text-[#d7bf90]">0{index + 1}</span><span>{step}</span></li>)}</ol></div></div></section>

      <section className="bg-[#27333b] px-6 py-20 sm:px-10 lg:px-14 lg:py-24"><div className="mx-auto grid max-w-[1370px] gap-10 lg:grid-cols-[1fr_0.8fr]"><div><p className="text-sm font-semibold uppercase tracking-[0.15em] text-[#d7bf90]">A shared standard</p><h2 className="mt-5 max-w-3xl text-[39px] font-light leading-[1.08] tracking-[-0.04em] sm:text-[54px]">Good surfaces are collaborative work.</h2></div><div className="space-y-5 text-[17px] leading-[1.75] text-white/70"><p>Every project brings together designers, site teams, suppliers and clients. We believe the most convincing results come from clear communication at each stage, before the first layer is applied.</p><p>That is why we stay close to the project from sample approval through execution, balancing creative intent with the realities of the site.</p></div></div></section>

      <section className="bg-[#f3efe8] px-6 pb-32 pt-20 text-[#1d2830] sm:px-10 lg:px-14 lg:pb-40 lg:pt-28"><div className="mx-auto max-w-[1370px]"><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><p className="text-sm font-semibold uppercase tracking-[0.15em] text-[#6a7375]">Where we work</p><h2 className="mt-5 max-w-2xl text-[40px] font-light leading-[1.06] tracking-[-0.04em] sm:text-[55px]">Residential, hospitality, retail and public spaces across India.</h2></div><Link href="/projects" className="border-b border-[#1d2830] pb-2 text-sm font-semibold uppercase tracking-[0.12em]">View projects →</Link></div><div className="mt-14 grid gap-4 sm:grid-cols-3"><div className="relative aspect-[1/1.1]"><Image src="/images/projects/botique-hotel-mumbai-interior.png" alt="Boutique hotel project" fill className="object-cover" sizes="33vw" /></div><div className="relative aspect-[1/1.1] sm:translate-y-12"><Image src="/images/projects/private villa goa/private-villa-goa-exterior.png" alt="Private villa project" fill className="object-cover" sizes="33vw" /></div><div className="relative aspect-[1/1.1]"><Image src="/images/projects/mtr eats bangalore/mtr-eats-bangalore-table-area.png" alt="Restaurant project" fill className="object-cover" sizes="33vw" /></div></div></div></section>
    </main>
  );
}
